armnn: add -Wno-error=uninitialized to CXXFLAGS
As of GCC 11, armnn generates the following compile error:

error: 'u32' is used uninitialized [-Werror=uninitialized]

so add the proper CXXFLAG to ignore this.

Signed-off-by: Chris Dimich <chris.dimich@boundarydevices.com>
(cherry picked from commit 267d1cb46d012bde317aabff510ef3963b573404)