packagegroup-fsl-ml: Mark MACHINE_SOCARCH specific
Upstream added a sanity check for allarch packagegroups

YoeDistro/poky@0562ab6

Fixes following errros:

ERROR: packagegroup-fsl-ml-1.0-r0 do_package_write_deb: An allarch
packagegroup shouldn't depend on packages which are dynamically renamed

Signed-off-by: Chris Dimich <chris.dimich@boundarydevices.com>
(cherry picked from commit 2950690aaf7674c5e53bee1af76d76fddc0b98f2)